## Chapter 1

# Vectors, Matrices, and Arrays

### 1.0 Introduction
Numpy is the foundation of the Python machine learning stack. It allows for efficient operations on the data structures often used in machine learning: vectors, matricies, and tensors.

This chapter covers the most common NumPy operations we are likely to run into

NumPy is the fast, optimized engine that drives the Python machine learning car. Standard Python lists are too slow for large-scale math.

Data types are categorized into two fundamental groups: Elementary (or Primitive) types, which are the basic building blocks holding single values (like Integers, Floats, and Booleans), and Compound (or Non-Primitive/Reference) types, which are structured collections built from primitive types. Compound types can be Linear (ordered sequences like Arrays, Lists, Strings, and Tuples), Non-Linear (relationships or unordered collections like Sets, Maps/Dictionaries , Trees, and Graphs), or complex, user-defined structures created through Classes/Objects that encapsulate both data and behavior.

In [ ]:
# using the for loop to add the numbers
total_sum = 0
for number in range(1, 11):
    total_sum += number
print (total_sum)

55


Create a vector

In [1]:
# load library
import numpy as np

# create a vector as a row
vector_row = np.array([1, 2, 3, 4, 5, 6, 7])

# create a vetor as a column
vector_column = np.array([[1],
                          [2],
                          [3],
                          [4],
                          [5]])
print (vector_row)
print (vector_column)

[1 2 3 4 5 6 7]
[[1]
 [2]
 [3]
 [4]
 [5]]


Numpy's main data structure is the multidimensional array- matrix 

In [2]:
# load library
import numpy as np

# create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
print(matrix)

[[1 2]
 [1 2]
 [1 2]]


Matrix: To create a matrix we can use a NumPy two-dimensional array. In our solution, the matrix contains three rows and two columns (a column of 1s and a column of 2s)

NumPy actually has a dedicated matrix data structure:

In [ ]:
## Error
#matrix_object = np.mat([[1, 2], [1, 2], [1, 2]])

Matrix data structure is not recommended for two reasons. First, arrays are the de facto standard data structure of NumPy. Second the vast majority of NumPy operations return arrays, not matrix objects.

1.3 Creating a Sparse Matrix
Given data with very few nonzero values, you want to efficiently represent it.

In [ ]:
# load libraries
import numpy as np
from scipy import sparse

# create a matrix
matrix = np.array([[0, 0],
                  [0, 1],
                  [3, 0]])

# create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


A frequent situation in machine learning is having a huge amount of data; however most of the elements in the data are zeros. For example, imagine a matrix where the columns are every movie on Netflix, the rows are every Netflix user, and the values are how many times a user has watched that particular movie. This matrix would have tens of thousands of columns and millions of rows! However, since most users do not watch most movies, the vast majority of elements would be zero.

Sparse matricies only store nonzero elements and assume all other values will be zero, leading to significant computational savings. In our solution, we created a Numpy array with two nonzero values, then converted it into a sparse matrix. If we view the sparse matrix we can see that only the nonzero values are stored:

In [ ]:
# view sparse matrix
print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


There are a number of types of sparse matrices. However, in compressed sparse row (CSR) matrices, (1, 1) and (2, 0) represent the (zero-indexed) indices of the non-zero values 1 and 3, respectively. For example, the element 1 is in the second row and second column. We can see the advantage of sparse matrices if we create a much larger matrix with many more zero elements and then compare this larger matrix with our original sparse matrix:

In [ ]:
# create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

# view original sparse matrix
print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [ ]:
# view larger sparse matrix
print(matrix_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


As we can see, despite the fact that we added many more zero elements in the larger matrix, its sparse representation is exactly the same as our original sparse matrix. That is, the addition of zero elements did not change the size of the sparse matrix.

1.4 Selected Elements

In [ ]:
# load library
import numpy as np

# create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# select the third element of vector
vector[2]

np.int64(3)

In [ ]:
# select second row, second column
matrix[1,1]

np.int64(5)

#### Discussion
Like most things in Python, NumPy arrays are zero-indexed, meaning that the index of the first element is 0, not 1. With that caveat, NumPy offers a wide variety of methods for selecting (i.e., indexing and slicing) elements or groups of elements in arrays:

In [ ]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [ ]:
# select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [ ]:
# select the last element
vector[-1]

6

In [ ]:
# select the first two rows and all columns of a matrix
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

### 1.5 Describing a Matrix
#### Problem
You want to describe the shape, size, and dimensions of the matrix

#### Solution
Use shape, size, and ndim:

In [ ]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# view number of rows and columns
matrix.shape

(3, 4)

In [ ]:
# view number of elements (rows * columns)
matrix.size

12

In [ ]:
# view number of dimensions
matrix.ndim

2

#### Discussion
This might seem basic (and it is); however, time and again it will be valuable to check the shape and size of an array both for further calculations and simply as a gut check after some operation

### 1.6 Applying Operations to Elements
#### Problem
You want to apply some function to multiple elements in an array.

#### Solutions
Use NumPy's vectorize:

In [ ]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# create function that adds 1000 to something
add_1000 = lambda i: i + 1000

# create vectorized function
vectorized_add_1000 = np.vectorize(add_1000)

# apply function to all elementsin matrix
vectorized_add_1000(matrix)

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

#### Discusion
NumPy’s vectorize class converts a function into a function that can apply to all elements in an array or slice of an array. It’s worth noting that vectorize is essentially a for loop over the elements and does not increase performance. Furthermore, NumPy arrays allow us to perform operations between arrays even if their dimensions are not the same (a process called broadcasting). For example, we can create a much simpler version of our solution using broadcasting:

In [ ]:
# add 1000 to all elements
matrix + 1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

### Finding Maximum and Minimum Values
#### Problem
You need to find the maximum or minimum value in an array.

#### Solution
Use NumPy's max and min:

In [ ]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# return maximum element
np.max(matrix)

np.int64(9)

In [ ]:
# return minimum element
np.min(matrix)

np.int64(1)

#### Discussion
Often we want to know the maximum and minimum value in an array or subset of an array. This can be accomplished with the max and min methods. Using the axis parameter we can also apply the operation along a certain axis:

In [ ]:
# find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [ ]:
# find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

### 1.8 Calculating the Average, Variance, and Standard Deviation

#### Problem
You want to calculate some descriptive statistics about an array.

#### Solution
Use NumPy's mean, var, and std:

In [ ]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# return mean
np.mean(matrix)

np.float64(5.0)

In [ ]:
# return variance
np.var(matrix)

np.float64(6.666666666666667)

In [ ]:
# return standard deviation
np.std(matrix)

np.float64(2.581988897471611)

#### Discussion
Just like with max and min, we can easily get descriptive statistics about the whole matrix or do calculations alon a single axis:

In [ ]:
# find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

### 1.9 Reshaping Arrays
#### Problem
You want to change the shape (number of rows and columns) of an array without changing the element values.

#### Solution
Use NumPy's reshape:

In [ ]:
# load library
import numpy as np

# create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

#### Discussion
reshape allows us to restructure an array so that we maintain the same data but it is organized as a different number of rows and columns. The only requirement is that the shape of the original and new matrix contain the same number of elements (i.e., the same size). We can see the size of a matrix using size:

In [ ]:
matrix.size

12

One useful argument in reshape is -1, which effectively means “as many as needed,” so reshape(-1, 1) means one row and as many columns as needed:

In [ ]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Finally, if we provide one integer, reshape will return a 1D array of that length:

In [ ]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 1.10 Transposing a Vector or Matrix
#### Problem
You need to transpose a vector or matrix

#### Solution
Use the T method:

In [ ]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Transposing is a common operation in linear algebra where the column and row indices of each element are swapped. One nuanced point that is typically overlooked outside of a linear algebra class is that, technically, a vector cannot be transposed because it is just a collection of values:

In [ ]:
# transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

However, it is common to refer to transposing a vector as converting a row vector to a column vector (notice the second pair of brackets) or vice versa:

In [ ]:
# transpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### 1.11 Flattening a Matrix
#### Problem
You need to transform a matrix into a one-dimensional array.

#### Solution
Use flatten:

In [ ]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Discussion
flatten is a simple method to transform a matrix into a one-dimensional array. Alternatively, we can use reshape to create a row vector:

In [ ]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 1.12 Finding the Rank of a Matrix
#### Problem
You need to know the rank of a matrix

#### Solution
Use NumPy's linear algebra method matrix_rank:

In [ ]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# return matrix rank
np.linalg.matrix_rank(matrix)

np.int64(2)

#### See Also
* The Rank of a Matrix, CliffsNotes (https://www.cliffsnotes.com/study-guides/algebra/linear-algebra/real-euclidean-vector-spaces/the-rank-of-a-matrix)

In [ ]:
# load library
import numpy as np

# create matricies
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# add two matricies
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [ ]:
# subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

#### Discussion
Alternatively, we can simply use the + and - operators:

In [ ]:
# add two matricies
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

### 1.19 Multiplying Matricies
#### Problem
You want to multiply two matrices.

#### Solution
Use NumPy's dot:

In [ ]:
# load library
import numpy as np

# create matrices
matrix_a = np.array([[1, 1],
                     [1, 2]])

matrix_b = np.array([[1, 3],
                     [1, 2]])

# multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

#### Discussion
Alternatively, in Python 3.5+ we can use the @ operator:

In [ ]:
# multiply two matrices
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

#### See Also
* Array vs Matrix Operations, MathWorks (https://www.mathworks.com/help/matlab/matlab_prog/array-vs-matrix-operations.html?requestedDomain=true)

### 1.21 Generating Random Values
#### Problem
You want to generate pseudorandom values.

#### Solution
Use NumPy's random:

In [ ]:
# load library
import numpy as np

# set seed
np.random.seed(0)

# generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

#### Discussion
NumPy offers a wide variety of means to generate random numbers, many more than can be covered here. In our solution we generated floats; however, it is also common to generate integers:

In [ ]:
# genereate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([8, 9, 4])

Alternatively, we can generate numbers by drawing them from a distribution:

In [ ]:
# draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-0.13309028,  0.44386323,  0.33367433])

In [ ]:
# draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([ 1.26875282, -2.0088733 ,  0.57502137])

In [ ]:
# draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.14335329, 1.94466892, 1.52184832])

Finally, it can sometimes be useful to return the same random numbers multiple times to get predictable, repeatable results. We can do this by setting the “seed” (an integer) of the pseudorandom generator. Random processes with the same seed will always produce the same output. We will use seeds throughout this book so that the code you see in the book and the code you run on your computer produces the same results.